import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {btree_gist} from '@electric-sql/pglite/contrib/btree_gist';

test('booking email outbox is transactional, private, deduplicated, and tracks cancellation independently',async()=>{
 const pg=new PGlite({extensions:{btree_gist}});
 try{
  await pg.exec(`create role anon;create role authenticated;create schema auth;create schema extensions;
   create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
   create function auth.uid() returns uuid language sql stable as $$ select (nullif(current_setting('request.jwt.claims',true),'')::jsonb->>'sub')::uuid $$;
   create function auth.jwt() returns jsonb language sql stable as $$ select coalesce(nullif(current_setting('request.jwt.claims',true),''),'{}')::jsonb $$;
   grant usage on schema auth to authenticated;grant execute on function auth.uid(),auth.jwt() to authenticated;`);
  for(const file of ['20261007192320_grooming_accounts_and_schedule.sql','20261007193157_grooming_status_conflict_response.sql','20261007205240_booking_emails.sql'])await pg.exec(await readFile(new URL('../supabase/migrations/'+file,import.meta.url),'utf8'));
  const admin=crypto.randomUUID(),client=crypto.randomUUID(),other=crypto.randomUUID(),demo=crypto.randomUUID();
  for(const id of [admin,client,other,demo])await pg.query('insert into auth.users values($1,$2,now())',[id,id+'@example.com']);
  await pg.query('insert into private.grooming_admins values($1)',[admin]);
  const as=(id,sql,args=[],anonymous=false)=>pg.transaction(async tx=>{await tx.exec('set local role authenticated');await tx.query("select set_config('request.jwt.claims',$1,true)",[JSON.stringify({sub:id,is_anonymous:anonymous})]);return tx.query(sql,args);});
  const day=new Date(Date.now()+7*86400000).toISOString().slice(0,10);
  const payload=()=>({requestKey:crypto.randomUUID(),ownerName:'Fictional Customer',phone:'+1 202 555 0140',email:'unverified-form-address@example.com',dogName:'Jake',breed:'Poodle',size:'Small',service:'Full groom',address:'12 Example Street, Demo City',preferredDate:day,timeWindow:'Morning',notes:'',website:''});
  const submit=async(id=client)=>(await as(id,'select public.grooming_submit_request($1::jsonb) as r',[JSON.stringify(payload())])).rows[0].r.id;
  const manage=(id,status,start=null)=>as(admin,'select public.grooming_manage_request($1,$2,$3,$4,$5)',[id,status,start,start?60:null,start?0:null]);
  const events=async(id)=>(await pg.query('select * from private.grooming_email_events where request_id=$1 order by created_at,id',[id])).rows;
  const row=async(id)=>(await as(client,'select * from public.grooming_requests where id=$1',[id])).rows[0];
  const claim=async(id,user=admin)=>(await as(user,'select public.grooming_claim_email($1) as r',[id])).rows[0].r;
  const finish=async(job,status,token=job.claimToken)=>(await as(admin,'select public.grooming_finish_email($1,$2,$3,$4,$5) as r',[job.eventId,token,status,status==='accepted'?'provider-fixture':null,status==='failed'?'provider_rejected':null])).rows[0].r;
  const first=await submit();
  await manage(first,'confirmed',day+'T10:00');
  assert.equal((await events(first)).length,1);
  assert.equal((await events(first))[0].recipient,client+'@example.com','recipient comes from verified account, not form contact email');
  await manage(first,'confirmed',day+'T10:00');
  await as(admin,'select public.grooming_manage_request($1,p_seen=>true)',[first]);
  assert.equal((await events(first)).length,1,'repeated confirmation and seen updates do not duplicate email intents');
  await assert.rejects(claim(first,client),e=>e.code==='42501');
  await assert.rejects(as(client,'select * from private.grooming_email_events'),e=>e.code==='42501');
  await assert.rejects(as(client,"select public.grooming_finish_email($1,$2,'accepted')",[crypto.randomUUID(),crypto.randomUUID()]),e=>e.code==='42501');
  const concurrent=await Promise.all([claim(first),claim(first)]);
  assert.deepEqual(concurrent.map(x=>x.status).sort(),['busy','claimed']);
  const job=concurrent.find(x=>x.status==='claimed');
  assert.equal((await finish(job,'accepted',crypto.randomUUID())).status,'stale');
  assert.equal((await finish(job,'accepted')).status,'accepted');
  assert.equal((await claim(first)).status,'accepted','accepted jobs cannot be sent again');
  assert.equal((await row(first)).notification_status,'accepted');
  await manage(first,'declined');
  const cancellation=await claim(first);
  assert.equal(cancellation.kind,'cancelled');assert.equal(cancellation.payload.scheduledAt,day+'T10:00');
  assert.equal((await events(first)).length,2);
  await finish(cancellation,'accepted');
  await manage(first,'new');
  assert.equal((await row(first)).notification_event_id,null);
  await manage(first,'confirmed',day+'T10:00');
  const later=await claim(first);
  await manage(first,'declined');
  assert.equal((await finish(later,'accepted')).status,'stale','old in-flight confirmation cannot overwrite newer cancellation');
  assert.equal((await row(first)).notification_kind,'cancelled');
  assert.equal((await row(first)).notification_status,'pending');
  await manage(first,'new');
  await manage(first,'confirmed',day+'T10:00');
  const second=await submit(other);
  await assert.rejects(manage(second,'confirmed',day+'T10:30'),e=>e.code==='23P01');
  assert.equal((await events(second)).length,0,'failed booking conflicts roll back their email intent');
  await manage(second,'declined');
  assert.equal((await events(second)).length,0,'declining an unconfirmed request is not a cancellation email');
  const expired=await claim(first);
  await pg.query("update private.grooming_email_events set locked_until=now()-interval '1 second',first_attempt_at=now()-interval '16 minutes' where id=$1",[expired.eventId]);
  assert.equal((await claim(first)).status,'uncertain','uncertain old attempts never cause blind duplicate sends');
  assert.equal((await row(first)).notification_status,'uncertain');
  await as(demo,'select public.grooming_seed_demo()',[],true);
  const sample=(await as(demo,"select id from public.grooming_requests where status='new' limit 1",[],true)).rows[0].id;
  await as(demo,"select public.grooming_manage_request($1,'confirmed',$2,60,0)",[sample,day+'T17:00'],true);
  assert.equal((await events(sample)).length,0,'demo never queues a real email');
  await assert.rejects(as(demo,'select public.grooming_claim_email($1)',[sample],true),e=>e.code==='42501');
  await as(admin,'select public.grooming_delete_request($1,true)',[first]);
  assert.equal((await events(first)).length,0,'request deletion also removes private outbox data');
 }finally{await pg.close();}
});
