'use client';
import { useEffect,useState,useCallback } from 'react';
import { PawPrint,CalendarDays,RefreshCw } from 'lucide-react';
import { SignOut } from '@/app/account-controls';
import type { Booking } from '@/lib/validation';
const labels={new:'Waiting for Kevin',confirmed:'Confirmed',completed:'Completed',declined:'Declined'};
function date(value:string){const stamp=/Z$|[+-]\d{2}:\d{2}$/.test(value);return new Date(stamp?value:value.slice(0,10)+'T12:00:00').toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric',year:'numeric',...(stamp?{timeZone:'America/New_York'}:{})})}
function time(value:string){const h=Number(value.slice(11,13));return `${h%12||12}:${value.slice(14,16)} ${h>=12?'PM':'AM'}`;}
export default function History(){
 const [rows,setRows]=useState<Booking[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const refresh=useCallback(async()=>{try{const r=await fetch('/api/client/requests',{cache:'no-store'});const d=await r.json() as {error?:string;requests:Booking[]};if(!r.ok)throw new Error(d.error||'Could not load your visits.');setRows(d.requests);setError('');}catch(e){setError(e instanceof Error?e.message:'Could not load your visits.')}finally{setLoading(false)}},[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),15000);return()=>clearInterval(timer)},[refresh]);
 return <><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><PawPrint size={23}/></span><span>Kevin’s<span className="brand-sub">MOBILE GROOMING</span></span></a><nav className="account-nav"><a className="text-link" href="/">Request a visit</a><SignOut/></nav></header><main className="customer-main"><div className="heading-row"><div><p className="eyebrow">YOUR ACCOUNT</p><h1>Your grooming visits</h1><p className="muted">Requests, confirmed appointments, and past visits. Confirmations and cancellations are emailed to your verified account address.</p></div><button className="secondary" onClick={()=>void refresh()}><RefreshCw size={17}/>Refresh</button></div>{error&&<p className="error" role="alert">{error} <a href="/login">Sign in again</a></p>}{loading?<p role="status">Loading your visits…</p>:rows.length===0?<section className="form-card customer-empty"><CalendarDays size={35}/><h2>Your first visit starts here</h2><p>Send Kevin a request. Your preferred date will be confirmed after you agree on availability and price.</p><a className="primary" href="/">Request a visit</a></section>:<div className="history-grid">{rows.map(row=><article key={row.id} className="form-card history-card"><div className="history-heading"><h2>{row.dog_name}</h2><span className={'status status-'+row.status}>{row.status==='declined'&&row.notification_kind==='cancelled'?'Cancelled':labels[row.status]}</span></div>{row.dog_photo&&<img className="booking-dog-photo" src={'/api/requests/'+row.id+'/photo'} alt={row.dog_name+' — your uploaded photo'}/>}<p>{row.service} · {row.breed}</p><div className="history-date"><CalendarDays size={20}/><div>{row.scheduled_at?<><strong>{date(row.scheduled_at)} at {time(row.scheduled_at)}</strong><p>{row.duration_minutes} minute visit · Service local time</p></>:<><strong>Preferred: {date(row.preferred_date)}</strong><p>{row.time_window}</p></>}</div></div>{row.status==='new'&&<p className="receipt-note">Your appointment is not confirmed yet. Kevin will contact you about the time and price.</p>}{row.status==='declined'&&<p className="fine">{row.notification_kind==='cancelled'?'Kevin cancelled this visit. This time is no longer reserved. Contact him to discuss another appointment.':'Kevin could not accept this request. Contact him to discuss another visit.'}</p>}<hr/><p className="fine">{row.address}</p>{row.notes&&<p className="care-notes">{row.notes}</p>}<p className="fine">Requested {date(row.created_at)} · Ref {row.id.slice(0,8).toUpperCase()}</p></article>)}</div>}</main></>;
}
