'use client';
import { useState,useEffect } from 'react';
import { PawPrint,LockKeyhole } from 'lucide-react';
export default function SignInForm({admin=false,passwordOnly=false}:{admin?:boolean;passwordOnly?:boolean}){
 const [mode,setMode]=useState('login'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{const p=new URLSearchParams(location.search);if(!admin&&['signup','recover'].includes(p.get('mode')||''))setMode(p.get('mode')!);if(p.has('callbackError'))setError('We could not finish signing you in from this link. If you confirmed your email, sign in below. For password recovery, request a new link and open it in the browser where you started.');},[admin]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;setBusy(true);setError('');setMessage('');const fields=Object.fromEntries(new FormData(form));const action=passwordOnly?'password':mode;try{const r=await fetch('/api/auth/'+action,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(action==='password'?{password:fields.password}:action==='recover'?{email:fields.email}:{email:fields.email,password:fields.password,...(admin?{admin:true}:{})})});const d=await r.json() as {error?:string;next?:string;message?:string};if(!r.ok)throw new Error(d.error||'Please try again.');form.reset();if(d.next)location.assign(d.next);else if(passwordOnly)location.assign('/account');else setMessage(d.message||'Done.');}catch(e){setError(e instanceof Error?e.message:'Could not connect. Please try again.')}finally{setBusy(false)}}
 const title=passwordOnly?'Choose a new password':mode==='signup'?'Create your customer account':mode==='recover'?'Reset your password':admin?'Admin sign in':'Welcome back';
 return <main className="auth-layout"><a className="brand" href="/"><span className="brand-icon"><PawPrint size={23}/></span><span>Kevin’s<span className="brand-sub">MOBILE GROOMING</span></span></a><section className="form-card auth-card"><span className="auth-icon"><LockKeyhole size={25}/></span><p className="eyebrow">{admin?'BUSINESS OWNER':'YOUR GROOMING VISITS'}</p><h1>{title}</h1><p className="muted">{passwordOnly?'Use at least 8 characters.':mode==='signup'?'Request visits and see your appointment history.':admin?'Review customer requests and manage Kevin’s schedule.':mode==='recover'?'We’ll send a recovery link if this email has an account.':'Sign in to keep track of your requests and confirmed visits.'}</p><form onSubmit={submit}>{!passwordOnly&&<label>Email<input type="email" name="email" autoComplete="email" required maxLength={150}/></label>}{(passwordOnly||mode!=='recover')&&<label>Password<input type="password" name="password" autoComplete={mode==='signup'||passwordOnly?'new-password':'current-password'} required minLength={8} maxLength={128}/></label>}{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="success" role="status">{message}</p>}<button className="primary full" disabled={busy}>{busy?'Please wait…':passwordOnly?'Save password':mode==='signup'?'Create account':mode==='recover'?'Send recovery link':'Sign in'}</button></form>{!passwordOnly&&<div className="auth-links">{mode==='login'?<><a href="/login?mode=recover">Forgot password?</a>{!admin&&<a href="/login?mode=signup">Create a customer account</a>}</>:<a href="/login">Back to sign in</a>}{admin?<a href="/login">Customer sign in</a>:<a href="/">Back to booking page</a>}</div>}</section></main>;
}
