import { access,demoSession } from '@/lib/auth';
import { db,json,sameOrigin,unavailable,runtime } from '@/lib/data';
import { bookingSchema } from '@/lib/validation';
export const dynamic='force-dynamic';
export async function GET(req:Request){try{const tenant=await access(new URL(req.url).searchParams.get('demo')==='1');if(!tenant)return json({error:'Please sign in to Kevin’s workspace.'},401);const data=await db().prepare('SELECT id, owner_name, phone, email, dog_name, breed, size, service, address, preferred_date, time_window, notes, status, scheduled_at, duration_minutes, travel_minutes, seen, created_at, updated_at FROM requests WHERE tenant = ? ORDER BY created_at DESC LIMIT 500').bind(tenant).all();return json({requests:data.results});}catch(e){return unavailable(e)}}
export async function POST(req:Request){try{if(!sameOrigin(req))return json({error:'Please submit from the booking page.'},403);if(Number(req.headers.get('content-length')||0)>16000)return json({error:'Request is too large.'},413);const raw=await req.text();if(raw.length>16000)return json({error:'Request is too large.'},413);let body;try{body=JSON.parse(raw)}catch{return json({error:'Please check the form and try again.'},400)}const parsed=bookingSchema.safeParse(body);if(!parsed.success)return json({error:parsed.error.issues[0].message},400);const demo=new URL(req.url).searchParams.get('demo')==='1';const tenant=demo?await demoSession():'kevin';if(!tenant)return json({error:'Your practice session expired. Open a new demo.'},401);const b=parsed.data;
const existing=await db().prepare('SELECT id FROM requests WHERE tenant = ? AND request_key = ?').bind(tenant,b.requestKey).first<{id:string}>();if(existing)return json({id:existing.id,status:'new'});
const hour=Math.floor(Date.now()/3600000);const ip=req.headers.get('cf-connecting-ip')||'local';const keyBytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode((runtime().DEMO_SECRET||'')+ip+hour+tenant));const key=Array.from(new Uint8Array(keyBytes)).map(x=>x.toString(16).padStart(2,'0')).join('');const quota=await db().prepare('INSERT INTO rate_limits (key,count,expires_at) VALUES (?,1,?) ON CONFLICT(key) DO UPDATE SET count=count+1 RETURNING count').bind(key,(hour+2)*3600000).first<{count:number}>();if((quota?.count||0)>20)return json({error:'Too many requests. Please try again later.'},429);
const id=crypto.randomUUID(),now=new Date().toISOString();await db().prepare('INSERT INTO requests (id,tenant,request_key,owner_name,phone,email,dog_name,breed,size,service,address,preferred_date,time_window,notes,status,seen,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,?,?) ON CONFLICT(tenant,request_key) DO NOTHING').bind(id,tenant,b.requestKey,b.ownerName,b.phone,b.email,b.dogName,b.breed,b.size,b.service,b.address,b.preferredDate,b.timeWindow,b.notes,'new',now,now).run();const saved=await db().prepare('SELECT id FROM requests WHERE tenant=? AND request_key=?').bind(tenant,b.requestKey).first<{id:string}>();return json({id:saved?.id,status:'new'},201);
}catch(e){return unavailable(e)}}
